/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Signal: brand/interactive accent (Connect, focus, active tab, links,
        // Agent Activity terminal chrome). Never used for BULL/BEAR meaning — see DESIGN.md §1.1.
        'signal':                     '#38bdf8',
        'signal-dim':                 '#7dd3fc',
        'signal-bright':              '#a6e6ff',
        'signal-deep':                '#0c4a6e',
        'on-signal':                  '#00263a',
        // Direction semantics: BULL/BEAR only, never reused as a generic interactive color.
        'bull':                       '#34d399',
        'bull-deep':                  '#059669',
        'bull-tint':                  '#0a2e22',
        'bear':                       '#fb7185',
        'bear-deep':                  '#be123c',
        'bear-tint':                  '#2e0a14',
        // Market-state semantics, centralized so StatusBadge etc. never hardcode hex.
        'locked':                     '#fbbf24',
        'on-surface-faint':           '#5b6280',
        'surface-dim':                '#0f131f',
        'tertiary-fixed-dim':         '#7bd0ff',
        'on-tertiary':                '#00354a',
        'on-error-container':         '#ffdad6',
        'primary-fixed':              '#59feae',
        'surface-bright':             '#353946',
        'on-secondary-container':     '#ffc2c1',
        'on-primary-fixed':           '#002111',
        'on-secondary-fixed-variant': '#920020',
        'on-primary':                 '#003921',
        'secondary':                  '#ffb3b2',
        'on-primary-container':       '#005332',
        'inverse-surface':            '#dfe2f3',
        'tertiary-container':         '#40c2fd',
        'surface-variant':            '#313442',
        'tertiary-fixed':             '#c4e7ff',
        'primary-container':          '#00d085',
        'surface':                    '#0f131f',
        'secondary-fixed-dim':        '#ffb3b2',
        'error':                      '#ffb4ab',
        'surface-container-low':      '#171b28',
        'on-surface-variant':         '#bacbbd',
        'surface-container':          '#1b1f2c',
        'on-background':              '#dfe2f3',
        'secondary-fixed':            '#ffdad9',
        'on-surface':                 '#dfe2f3',
        'on-tertiary-fixed':          '#001e2c',
        'surface-tint':               '#31e194',
        'on-secondary-fixed':         '#410008',
        'tertiary':                   '#9bdaff',
        'on-primary-fixed-variant':   '#005231',
        'on-error':                   '#690005',
        'background':                 '#0f131f',
        'on-secondary':               '#680013',
        'inverse-on-surface':         '#2c303d',
        'outline':                    '#859589',
        'surface-container-lowest':   '#0a0e1a',
        'primary-fixed-dim':          '#31e194',
        'outline-variant':            '#3c4a40',
        'inverse-primary':            '#006d43',
        'error-container':            '#93000a',
        'surface-container-high':     '#262a37',
        'secondary-container':        '#b5032a',
        'on-tertiary-container':      '#004d6a',
        'primary':                    '#43ed9f',
        'surface-container-highest':  '#313442',
        'on-tertiary-fixed-variant':  '#004c69',
      },
      borderRadius: {
        DEFAULT: '4px',
        lg:      '4px',
        xl:      '8px',
        full:    '9999px',
      },
      spacing: {
        gutter:         '1rem',
        'margin-x':     '2rem',
        'stack-lg':     '1.5rem',
        'container-max':'1440px',
        'stack-md':     '1rem',
        'stack-xs':     '0.25rem',
        'stack-sm':     '0.5rem',
      },
      fontFamily: {
        'headline-md': ['Inter', 'sans-serif'],
        'data-sm':     ['"JetBrains Mono"', 'monospace'],
        'body-md':     ['Inter', 'sans-serif'],
        'body-sm':     ['Inter', 'sans-serif'],
        'data-lg':     ['"JetBrains Mono"', 'monospace'],
        'label-caps':  ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'data-md':     ['"JetBrains Mono"', 'monospace'],
        'data-xl':     ['"JetBrains Mono"', 'monospace'],
        'display-num': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'data-sm':     ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '400' }],
        'body-md':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm':     ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'data-lg':     ['18px', { lineHeight: '24px', fontWeight: '500' }],
        'label-caps':  ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'data-md':     ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'data-xl':     ['36px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-num': ['56px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      keyframes: {
        blink: { '0%, 49%': { opacity: 1 }, '50%, 100%': { opacity: 0 } },
      },
      animation: {
        blink: 'blink 1.1s steps(1) infinite',
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
}
